# Generated by Django 5.2.5 on 2025-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greek_word', models.CharField(help_text='The word in Greek', max_length=100, unique=True)),
                ('russian_translation', models.CharField(help_text='The Russian translation', max_length=100)),
                ('score', models.IntegerField(default=0, help_text='Score for tracking success. +1 for correct, -1 for incorrect.')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
